import { v4 as uuid } from "uuid";

export const products = [
  // Indian Category
  {
    _id: uuid(),
    title: "Butter Chicken",
    description:
      "Tender chicken cooked in a rich and creamy tomato-based sauce.",
    price: "250",
    categoryName: "Indian",
    isVegetarian: false,
  },
  {
    _id: uuid(),
    title: "Biryani",
    description: "Fragrant rice dish with spices and meat or vegetables.",
    price: "200",
    categoryName: "Indian",
    isVegetarian: false,
  },
  {
    _id: uuid(),
    title: "Palak Paneer",
    description: "Creamy spinach curry with cottage cheese cubes.",
    price: "180",
    categoryName: "Indian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Masala Dosa",
    description: "Thin rice crepes filled with spiced potato masala.",
    price: "150",
    categoryName: "Indian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Chole Bhature",
    description: "Deep-fried bread with spicy chickpea curry.",
    price: "160",
    categoryName: "Indian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Tandoori Chicken",
    description: "Marinated chicken cooked in a clay oven (tandoor).",
    price: "280",
    categoryName: "Indian",
    isVegetarian: false,
  },
  {
    _id: uuid(),
    title: "Paneer Tikka",
    description: "Grilled cottage cheese cubes marinated in spices.",
    price: "220",
    categoryName: "Indian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Rajma Chawal",
    description: "Kidney bean curry served with steamed rice.",
    price: "170",
    categoryName: "Indian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Gulab Jamun",
    description: "Deep-fried milk dumplings soaked in sugar syrup.",
    price: "120",
    categoryName: "Indian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Mango Lassi",
    description: "Refreshing yogurt-based drink with sweet mango flavor.",
    price: "90",
    categoryName: "Indian",
    isVegetarian: true,
  },

  // Chinese Category
  {
    _id: uuid(),
    title: "Sweet and Sour Chicken",
    description:
      "Crispy chicken pieces coated in a tangy sweet and sour sauce.",
    price: "180",
    categoryName: "Chinese",
    isVegetarian: false,
  },
  {
    _id: uuid(),
    title: "Fried Rice",
    description:
      "Stir-fried rice with vegetables, egg, and choice of meat or tofu.",
    price: "150",
    categoryName: "Chinese",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Kung Pao Chicken",
    description: "Spicy stir-fried chicken with peanuts and vegetables.",
    price: "200",
    categoryName: "Chinese",
    isVegetarian: false,
  },
  {
    _id: uuid(),
    title: "Mapo Tofu",
    description: "Soft tofu and minced meat cooked in a spicy sauce.",
    price: "160",
    categoryName: "Chinese",
    isVegetarian: false,
  },
  {
    _id: uuid(),
    title: "Spring Rolls",
    description: "Crispy fried rolls filled with vegetables or meat.",
    price: "120",
    categoryName: "Chinese",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Peking Duck",
    description: "Roasted duck with crispy skin served with pancakes.",
    price: "300",
    categoryName: "Chinese",
    isVegetarian: false,
  },
  {
    _id: uuid(),
    title: "Hot and Sour Soup",
    description: "Spicy and tangy soup with mushrooms, tofu, and vegetables.",
    price: "100",
    categoryName: "Chinese",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Chow Mein",
    description:
      "Stir-fried noodles with vegetables and choice of meat or tofu.",
    price: "170",
    categoryName: "Chinese",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Dim Sum",
    description: "Assortment of bite-sized dumplings and steamed dishes.",
    price: "220",
    categoryName: "Chinese",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Szechuan Beef",
    description:
      "Spicy beef stir-fry with Szechuan peppercorns and vegetables.",
    price: "250",
    categoryName: "Chinese",
    isVegetarian: false,
  },

  {
    _id: uuid(),
    title: "Margherita Pizza",
    description:
      "Classic pizza topped with tomato sauce, mozzarella, and fresh basil.",
    price: "300",
    categoryName: "Italian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Pasta Carbonara",
    description:
      "Spaghetti with creamy egg-based sauce, pancetta, and Parmesan cheese.",
    price: "250",
    categoryName: "Italian",
    isVegetarian: false,
  },
  {
    _id: uuid(),
    title: "Ravioli",
    description:
      "Stuffed pasta pockets with various fillings like cheese or meat.",
    price: "280",
    categoryName: "Italian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Lasagna",
    description:
      "Layers of pasta, meat or vegetables, and cheese baked to perfection.",
    price: "320",
    categoryName: "Italian",
    isVegetarian: false,
  },
  {
    _id: uuid(),
    title: "Tiramisu",
    description:
      "Classic Italian dessert with layers of ladyfingers, mascarpone cream, and coffee.",
    price: "180",
    categoryName: "Italian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Bruschetta",
    description:
      "Toasted bread topped with fresh tomatoes, basil, and olive oil.",
    price: "120",
    categoryName: "Italian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Gelato",
    description: "Traditional Italian ice cream with various flavors.",
    price: "100",
    categoryName: "Italian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Caprese Salad",
    description:
      "Fresh salad with tomatoes, mozzarella cheese, and basil leaves.",
    price: "200",
    categoryName: "Italian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Panna Cotta",
    description: "Creamy and silky Italian dessert with a hint of vanilla.",
    price: "150",
    categoryName: "Italian",
    isVegetarian: true,
  },
  {
    _id: uuid(),
    title: "Prosciutto e Melone",
    description: "Thinly sliced prosciutto wrapped around sweet melon slices.",
    price: "220",
    categoryName: "Italian",
    isVegetarian: false,
  },
];
